version: '2'

jobs:
  build:
    machine: true
    branches:
      only:
        - master
        - /pull-req\/.*/
        - /release\/.*/
        - /hotfix\/.*/
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn flow
      - run: yarn test
